data:
  train_bs: 1
  train_width: 512
  train_height: 512
  meta_paths:
    - 'HDTF/data/hdtf_clip.json'
    # - 'hdtf_3kps.json'
    # - 'part_01_wo_low_res_wo_low_syncnet_conf.json'
    # - 'p2.json'
    # - 'p3.json'
  flip_rate: 0.5
  sample_rate: 1
  num_frames: 20
  reference_margin: 30
  num_padding_audio_frames: 2
  lip_loss_weight: 1
  audio_embeddings_type: 'global' # {global}
  reference_drop_rate: 0
  kps_drop_rate: 0

module_training:
  denoising_unet: False
  reference_net: False
  v_kps_guider: False
  audio_projection: True
  motion_module: True

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16' # [fp16, bf16, fp32]
  enable_xformers_memory_efficient_attention: True
  reference_net_gradient_checkpointing: False
  denoising_unet_gradient_checkpointing: True
  max_train_steps: 140000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-6
  scale_lr: False
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay: 1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 20

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: 'scaled_linear'
  steps_offset: 1
  clip_sample: false

base_model_path: './pretrained_model/sd-image-variations-diffusers'
vae_model_path: './pretrained_model/sd-vae-ft-mse/'
audio_encoder_path: './pretrained_model/wav2vec2-base-960h/'

reference_net_path: './exp_output/stage_1-to-22k/reference_net-22001.pth'
denoising_unet_path: './exp_output/stage_1-to-22k/denoising_unet-22001.pth'
denoising_unet_state_dict_type: 'new_attn' # {moore_pretrained, old_attn, new_attn}
motion_module_path: './pretrained_model/animatediff/mm_sd_v15_v2.ckpt'
v_kps_guider_path: './exp_output/stage_1-to-22k/v_kps_guider-22001.pth'
audio_projection_path: './exp_output/stage_1-to-22k/audio_projection-22001.pth'

train_stage: 'stage_2'
save_all: True

weight_dtype: 'fp16' # [fp16, bf16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True
stage1_ckpt_dir:
stage1_ckpt_step: 283494

seed: 42
resume_from_checkpoint: 'latest' # 'latest'
checkpointing_steps: 2000
output_dir: './exp_output'
